server:
  port: 8602
spring:
  application:
     name: authserver
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true


eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

        
# SECURITY
security:
  unprotected-paths: /heartbit , /oauth/** , /oauth/token , /oauth/token_key , /user, /actuator/**
  jwt:
    resource-id: stegerilumination_resource 
  encoding-strength: 10
  security-realm: inventario
  oauth2:
    resource:
      user-info-uri:  http://localhost:8602/user 
      preferTokenInfo: true
      jwt:        key-uri: http://localhost:8602/oauth/token_key
      
# LOGGER
logging:
  level:
    ROOT: DEBUG
    org.springframework.web: debug
    org.springframework.security: trace
    com.auth.project.config.security: debug
    hibernate: 
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # IMPRIME LOS DATOS ENTRANTES A HIBERNATE 